version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 9000:80

  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - 6379:6379

  redis-performance:
    image: artarkatesoft/redis-study-redis-performance
    environment:
      SPRING_PROFILES_ACTIVE: local-cache
      SPRING_REDIS_HOST: redis
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/product_db
    ports:
      - 8080:8080

  business-metrics:
    image: artarkatesoft/redis-study-business-metrics
    environment:
      SPRING_REDIS_HOST: redis
    ports:
      - 8082:8080

volumes:
  postgres_data:
  pgadmin_data:
