version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - 6379:6379

  city-api:
    image: artarkatesoft/art-vinsguru-city-api
    ports:
      - 3030:3030